### ISSUE TITLE
Need better security to prevent outsiders from getting access to data

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#11]
Currently, the API is setup that if somebody gets access to our hostname, ports, and knows how to use our endpoints (which they will from the docs), they could get access to data that they shouldn't be able to.

Thoughts, @ankitr?

**Comment by ankitr** [comment]
What specifically can they access that they shouldn't be able to?

**Comment by gmittal** [comment]
`/api/getRequests/:number` sends back a list of cases and their information (the GET endpoint is supposed to be used in the volunteer app).

**Comment by ankitr** [comment]
In theory, mailroom isn't exposed to the web, but instead on a private network where it can be accessed by concierge and volunteer (because both have their own webservers). Does this make sense with what you were thinking?

**Comment by gmittal** [comment]
Oh, If they're on a private network then it should be fine. I for some reason thought we needed to publicly expose certain aspects. Just ignore this then.
