### ISSUE TITLE
Setup inbound email webhooks

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#13]
Can we have a Gmail address (or set it up through SendGrid, but since we already have Gmail it might be easier) that makes a POST request to `/communication/incoming/email/` with the message body and sender metadata? It will allow the system to keep track of the conversation between volunteers and users better.

@ankitr, thoughts?

**Comment by ankitr** [comment]
Can we have the SendGrid emails on a subdomain of copilot.help to allow us to use both mail servers?

**Comment by gmittal** [comment]
Yes, we can change the outbound email of SendGrid to `support.copilot.help` or something like that. Then when the user responds it would send the email through that domain.

**Comment by gmittal** [comment]
We basically need to satisfy SendGrid's requirements here: https://sendgrid.com/docs/API_Reference/Webhooks/parse.html

Otherwise we get Mail Delivery Subsystem errors.

**Comment by ankitr** [comment]
I'll set up the MX servers for support.copilot.help.

**Comment by ankitr** [comment]
Is there a strong reason to prefer the Web API instead of the SMTP API? The latter is much easier to integrate.

**Comment by gmittal** [comment]
The main goal is just to have inbound emails trigger a POST webhook on the mailroom's end that we can manage. If SendGrid's SMTP API can satisfy this requirement with greater ease, then I don't see a reason why not to use it.

**Comment by ankitr** [comment]
I understand. I've set up the mail servers for support.copilot.help, so all the emails should be parsed just fine. Not sure if you have to set anything up on your end with the settings.

**Comment by gmittal** [comment]
I haven't done anything with the settings yet. Will try and set something up.
