### ISSUE TITLE
stripEmail() function does not remove unnecessary conversation body

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#27]
When an email hits the `/communcation/incoming/email/` webhook, it usually contains the email message body in addition to the entire conversation. Clients like Gmail do a good job of only displaying the important information (the message body). 

![hidden](https://puu.sh/qerZJ/704ac96262.png)

`stripEmail()` is supposed to do this, except currently it's not doing a very good job of that. It removes the entire email body (including the important stuff). Need to find out how Gmail does it and implement the same functionality in `stripEmail()`

**Comment by ankitr** [comment]
IIRC, the temporary fix is to save the full body to firebase, including quoted information. (Naturally, this is suboptimal.)

**Comment by gmittal** [comment]
Suggested solution [here](http://stackoverflow.com/questions/14916618/extract-email-message-itself-from-all-its-prior-messages-and-meta-data-sendgrid).

**Comment by gmittal** [comment]
Apparently this is a really good library, except it's written in Ruby. https://github.com/github/email_reply_parser

**Comment by gmittal** [comment]
Found a Node.js port of the library: https://www.npmjs.com/package/emailreplyparser

**Comment by gmittal** [comment]
@ankitr PTAL at the known issues of email parser and let me know if we should plan on using it.

**Comment by ankitr** [comment]
Let's give it a try. If the node port doesn't work too well, lemme know and i'll install ruby on the server.

**Comment by gmittal** [comment]
Works really well actually.
