### ISSUE TITLE
validateRequestParameters logic errors

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#41]
I believe a fix made in #34 now has logic errors. The following conditional is causing `valid` to be set to `false` when it should be `true`:

``` javascript
if (typeof(schema[field]) !== typeof(body[field])) {
    valid = false;
    reason = "Invalid parameter type " + typeof(body[field]) + " that should be " + typeof(schema[field]) + ".";
    break;
}
```

I know the old code was less clean, but this is an urgent fix.

@ankitr?

**Comment by ankitr** [comment]
Can you explain this to me? I assumed the body field would need to be the same type as the schema field, so when they aren't equal then it would be invalid, right?

**Comment by ankitr** [comment]
Can you give more info as to what the issue specifically is? It looks to me that there is actually no change in the logic, so it seems that the condition `typeof(schema[field]) !== typeof(body[field])` is inherently wrong and the block simply never reached that point. I'm not sure. When does this cause issues?

**Comment by gmittal** [comment]
Our client-side concierge form by default sends up numbers (like user age) as strings, and `validateRequestParameters` checks to see if those strings are actually numbers by running `isNaN` and `parseInt`. This conditional comes right after, but sees that the schema and body age field are not the same, thus setting valid to false. 

Changing the conditional above to this might do the trick:

``` javascript
if ((typeof(schema[field]) !== typeof(body[field])) && (typeof(schema[field]) === "number" && typeof(body[field]) === "string")) {
    valid = false;
    reason = "Invalid parameter type " + typeof(body[field]) + " that should be " + typeof(schema[field]) + ".";
    break;
}
```
