### ISSUE TITLE
Finish fixing the lint errors

### ISSUE THREAD

**Issue by ankitr** [ProjectCopilot/mailroom#51]
There are more than enough lint errors left in this project, which will all eventually warrant a fix or an update to our lint rules. We're probably going to have some arguments.

**Comment by gmittal** [comment]
Such perfection.

**Comment by gmittal** [comment]
Have you tried linting the copilot submodules (like communications and prioritize)?

**Comment by ankitr** [comment]
Yup. All the easy fixes are done. I'm going through and fixing the harder ones.
