### ISSUE TITLE
Fallback communication server during outages

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#52]
We have this implemented for outbound volunteer messages. Whenever the mailroom goes down any volunteer based messages are scheduled in the Firebase to be sent as soon as the mailroom starts up again. 

We should have a fallback server (this is an available option in Twilio and SendGrid) that responds with a "Server is down" (or some equivalent) if an SMS or email user sends a message while mailroom is down.

**Comment by ankitr** [comment]
Is there no option for a default message from twilio or sendgrid when the server is down? I think it's kind of odd to have a backup server for something like this.

**Comment by gmittal** [comment]
Looking into it.

**Comment by gmittal** [comment]
@ankitr I believe you were planning on writing a PhantomJS script for this?

**Comment by gmittal** [comment]
^^ @ankitr 

Nice to be picking up on all of these issues 5 months later.
