### ISSUE TITLE
Consider new email templates

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#64]
http://htmlemail.io looks really nice (unfortunately costs money)

**Comment by ankitr** [comment]
Pretty expensive... $40 for the pack. Do you think it's worth?

**Comment by gmittal** [comment]
I'll take a closer look, it might be possible to rebuild these on our own.

**Comment by ankitr** [comment]
Our templates look fine on mobile now right?

**Comment by gmittal** [comment]
When I designed them two years ago, they were optimized for both mobile/desktop. I believe they should work. I'm also waiting on the logo from our designer.

**Comment by gmittal** [comment]
For now, we don't need these.
