### ISSUE TITLE
Does not return "failed to send message" error

### ISSUE THREAD

**Issue by gmittal** [ProjectCopilot/mailroom#81]
The system should have a method of letting volunteers know if a message did not go through. Currently it just fails silently.

**Comment by ankitr** [comment]
Can we assign this to one of our recruits?

**Comment by gmittal** [comment]
Almost certainly.

**Comment by gmittal** [comment]
@johnguibas Good initial back-end patch when you get the chance.

**Comment by gmittal** [comment]
Requires patches on both ```mailroom``` and ```volunteer```.
